### ISSUE TITLE
A bug that prevents other mod from wroking properly.

### ISSUE THREAD

**Issue by ReDece** [fantahund/VoxelMap#12]
mod list:EssentialGUI-1.9.1,voxelmap-1.12.13
version:minecraft1.12.1-fabric0.15.0

description:When I use both mods at the same time,the advanced block nbt function of the EssentialGUI mod will fail to render,and all the text in its tooltip box will disappear,leaving the entire text box pitch black.

When I use other minimap mod,this situation does not occur,so I think I need to provide feedback here.Can you provide a solution?thx.

And if needed,I can provide screenshots.Thank you again.

**Comment by fantahund** [comment]
I can't reproduce the problem, I also tested it in 1.20.1 with the same mod versions as you. So I need some more information. But you are welcome to try if it is still broken with the current 1.21 Voxelmap version.

![](https://fantacs.de/i/Pelicinuspetrel2613.png)

**Comment by ReDece** [comment]
Sorry, forgive me for using the wrong words.
What I mean is the Context Menu in the EssentialGUI mod (default key is Alt).When the crosshair points towards a block, holding on Alt will display a tooltips box brought by the EssentialGUI mod.
When I use EssentialGUI and Voxelmap together, the tooltips box will encounter rendering issues, as shown in the attached image.
![2024-06-28_17 37 38](https://github.com/fantahund/VoxelMap/assets/139113328/9f58b810-a797-43e0-bacc-24de65d9611a)
This time, when reproducing, I found that if the main hand holds an item, it will render normally, as shown in the following image.
![2024-06-28_17 37 40](https://github.com/fantahund/VoxelMap/assets/139113328/1085b053-4501-4e00-975d-32f08724fb53)
Because I have already upgraded my MC version, this reproduction was done under version 1.20.4,At the end, I will attach the log file. I hope this will be helpful in solving the problem.
The following is a list of modules:
	- essentialgui 1.9.6+1.20.4
	- fabric-api 0.97.0+1.20.4
	- voxelmap 1.20.4-1.12.17
[latest.log](https://github.com/user-attachments/files/16027791/latest.log)

**Comment by fantahund** [comment]
I can't get it reproduced. Can you please send me your options.txt from your Minecraft directory and the Confic file for the Voxelmap and the Essentials GUI from the Config folder?

**Comment by ReDece** [comment]
Of course.
This is the options.txt of minecraft:
[options.txt](https://github.com/user-attachments/files/16028110/options.txt)

These are configs of mods:
[essentialgui.json](https://github.com/user-attachments/files/16028122/essentialgui.json)
[voxelmap.txt](https://github.com/user-attachments/files/16028126/voxelmap.txt)
(GitHub doesn't seem to support uploading files with the .properties suffix, so I changed the suffix to .txt)

**Comment by fantahund** [comment]
At least I found out something. It is due to 3 settings that you have made in the EssentialsGUI mod. All of them have something to do with the weather. If I set the 3 values back to the default values, everything works.  

I'll have a look right away, but I'm not sure if it's directly due to the voxelmap, but we'll find out. :>

```
  "biomeWeatherTime": false, <---- Broke
  "biomeWeatherTimeHudLocation": "screen.hud_location.top_center", <---- Broke
  "biomeWeatherTimeTextureType": "screen.hud_texture_type.dark", <---- Broke
```

**Comment by fantahund** [comment]
But not so easy EssentialsGUI is not public I have no reasonable chance to look into the source code.

**Comment by fantahund** [comment]
I wrote to Lord_Rius, the developer of EssentialsGUI, on Reddit, maybe he'll take a look here.

**Comment by lordrius** [comment]
Hi! I'm the developer of EssentialGUI,

Just trying to reproduce the issue and I can confirm that it happens with latest version of VoxelMap (1.21-1.13.1) and my latest development version of EssentialGUI for 1.21. I will go deeper in my testing but for now I can tell the following...

-> It only happens when EssentialGUI renders the tooltip gui (DrawContext#drawTooltip) but I discover some interesting things:

For the side of VoxelMap:

It only happens if you set the map size larger than 'Small'. The scaling code seems affecting the text part of the Block/Entity Advanced Properties.

For the side of EssentialGUI:

- If you set the **Block/Entity Advanced Properties Hud Style to EssGui** it doesn't happen.
- If you enable the Biome/Weather/Time section and sets it position to upper-left or botton-right (screen visible) it works fine.

I was able to reproduce this **with or without any item in hand in 1.21**. I need more time to reproduce it in older versions.

**Comment by fantahund** [comment]
hey @ReDece try the last devbuild ^^ [https://jenkins.fantacs.de/job/VoxelMap/](https://jenkins.fantacs.de/job/VoxelMap/)
